name: telemed_app
description: Aplicativo para controle de caixa de remédios.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  flutter_secure_storage: ^10.3.1
  flutter_local_notifications: ^22.0.1
  timezone: ^0.11.1
  universal_html: ^2.3.0
  open_filex: ^4.7.0
  firebase_core: ^4.12.1
  firebase_messaging: ^16.4.3
  mobile_scanner: ^7.4.0
  alarm: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/audio/remindcare_alarm.mp3
    - assets/images/remindcare_logo.png
    - assets/bulario_brasil.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/remindcare_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/remindcare_logo.png"
  remove_alpha_ios: true